import type { MemberLocale } from './i18n';

/** Extra copy for redesigned admin member pages (merged with memberCopy at runtime). */
export const adminMemberUiCopy: Record<
	MemberLocale,
	Record<string, string>
> = {
	en: {
		adminBreadcrumbAddMember: 'Add member',
		adminBreadcrumbEditProfile: 'Edit profile',
		adminMemberDetailBack: '← Members',
		adminRecordPaymentTitle: 'Record payment',
		adminRecordPaymentSubtitle: '{{name}} · {{year}} {{tier}} membership',
		adminDonationPortionLabel: 'Donation portion',
		adminDonationPortionHint: 'Leave blank if entire amount is dues.',
		adminPaymentRefNotesLabel: 'Reference / notes',
		adminPaymentRefNotesPlaceholder: 'Confirmation number, envelope ref, etc.',
		adminMethodOther: 'Other',
		adminPaymentStatusPending: 'Pending payment',
		adminPaymentStatusNow: 'Record payment now (cash, e-transfer, cheque…)',
		adminActivationHint:
			'Payment will activate the membership immediately if it meets or exceeds the standard dues amount.',
		adminVotingLakeWarning:
			'A lake address is required for voting membership. You can add it now or update the profile later.',
		adminCancelForm: 'Cancel',
		adminSecondaryContactSection: 'Secondary contact',
		adminSecondaryContactNote: 'Optional — for record-keeping and email list purposes.',
		adminLakeAddressSection: 'Lake address',
		adminLakeAddressVotingNote: 'Required for voting membership.',
		adminDetailEmailOptInLabel: 'Email opt-in',
		adminEmailOptInYes: 'Yes',
		adminEmailOptInNo: 'No — opted out',
		adminEmailOptInAdmin: 'Opted in to association emails',
		adminInternalNotesLabel: 'Internal notes',
		adminInternalNotesPlaceholder: 'Visible to admins only.',
		adminMemberSince: 'Member since {{year}}',
		adminEmailOptedOut: '(opted out)',
		adminNotesView: '(view)',
		adminDisabledNotice: 'This member is disabled and hidden from all views.',
		adminReEnable: 'Re-enable',
		adminEditProfile: 'Edit profile',
		adminMembershipYearHeading: '{{year}} membership',
		adminAwaitingPayment: 'Awaiting payment — created {{date}}',
		adminCancelPendingMembership: 'Cancel pending membership',
		adminCancelPendingConfirm: 'Delete this pending membership? This cannot be undone.',
		adminNoMembershipYear: 'No membership for {{year}} yet.',
		adminAddVotingMembership: 'Add voting membership',
		adminAddAssociateMembership: 'Add associate membership',
		adminPreviousYears: 'Previous years',
		adminAddYearMembership: '+ Add membership for another year',
		adminModalAddMembershipTitle: 'Add membership for another year',
		adminTotalReceived: 'Total received',
		adminDuesDonationLine: '{{dues}} dues · {{don}} donation',
		adminAdminActionsLabel: 'Admin actions',
		adminDisableMember: 'Disable member',
		adminEnableMember: 'Re-enable member',
		adminGrantAdmin: 'Grant admin role',
		adminGrantAdminNoUser: 'Member has no linked sign-in account.',
		adminAdminActionsFootnote:
			'Disabling hides this member from all views. Admin role grants full access to this administration panel.',
		adminConfirmDisable: 'Disable this member? They will be hidden from all views.',
		adminConfirmEnable: 'Re-enable this member?',
		adminConfirmGrantAdmin: 'Grant this member full admin access to the membership console?',
		adminLakeManualLink: 'Enter address manually →',
		adminLakeSearchLink: '← Use address search',
		adminLakeConfirmedLabel: 'Selected address',
		adminProfileCardTitle: 'Profile',
		adminMembershipCardTitle: 'Membership',
		adminPaymentRadioLabel: 'Payment status',
		adminYearSelectLabel: 'Year',
		adminTierSelectLabel: 'Type',
		adminPrimaryContactSection: 'Primary contact',
		adminPreferencesSection: 'Preferences and notes',
		adminEditSubtitle: 'Edit profile',
		adminAccordionExpand: 'Show payments',
		adminCardPaymentStripe: 'Card (Stripe)',
		adminDetailLoading: 'Loading…',
		adminNoEmailDash: '—',
		adminNotesEmpty: '',
		adminConfirmDeletePayment: 'Delete this payment record?',
	},
	fr: {
		adminBreadcrumbAddMember: 'Ajouter un membre',
		adminBreadcrumbEditProfile: 'Modifier le profil',
		adminMemberDetailBack: '← Membres',
		adminRecordPaymentTitle: 'Enregistrer un paiement',
		adminRecordPaymentSubtitle: '{{name}} · Adhésion {{year}} — {{tier}}',
		adminDonationPortionLabel: 'Portion don',
		adminDonationPortionHint: 'Laisser vide si tout le montant est la cotisation.',
		adminPaymentRefNotesLabel: 'Référence / notes',
		adminPaymentRefNotesPlaceholder: 'No de confirmation, référence de l’enveloppe, etc.',
		adminMethodOther: 'Autre',
		adminPaymentStatusPending: 'Paiement en attente',
		adminPaymentStatusNow: 'Enregistrer un paiement maintenant (argent, virement, chèque…)',
		adminActivationHint:
			'Le paiement activera l’adhésion immédiatement s’il atteint ou dépasse la cotisation standard.',
		adminVotingLakeWarning:
			'Une adresse au lac est requise pour un droit de vote. Vous pouvez l’ajouter maintenant ou compléter le profil plus tard.',
		adminCancelForm: 'Annuler',
		adminSecondaryContactSection: 'Contact secondaire',
		adminSecondaryContactNote: 'Facultatif — pour les dossiers et la liste de diffusion.',
		adminLakeAddressSection: 'Adresse au lac',
		adminLakeAddressVotingNote: 'Obligatoire pour le droit de vote.',
		adminDetailEmailOptInLabel: 'Inscription aux courriels',
		adminEmailOptInYes: 'Oui',
		adminEmailOptInNo: 'Non — désinscrit',
		adminEmailOptInAdmin: 'Inscrit aux courriels de l’association',
		adminInternalNotesLabel: 'Notes internes',
		adminInternalNotesPlaceholder: 'Visibles des administrateurs seulement.',
		adminMemberSince: 'Membre depuis {{year}}',
		adminEmailOptedOut: '(désinscrit)',
		adminNotesView: '(voir)',
		adminDisabledNotice: 'Ce membre est désactivé et masqué partout.',
		adminReEnable: 'Réactiver',
		adminEditProfile: 'Modifier le profil',
		adminMembershipYearHeading: 'Adhésion {{year}}',
		adminAwaitingPayment: 'En attente de paiement — créée le {{date}}',
		adminCancelPendingMembership: 'Annuler l’adhésion en attente',
		adminCancelPendingConfirm: 'Supprimer cette adhésion en attente ? Cette action est irréversible.',
		adminNoMembershipYear: 'Aucune adhésion pour {{year}} pour le moment.',
		adminAddVotingMembership: 'Ajouter une adhésion avec droit de vote',
		adminAddAssociateMembership: 'Ajouter une adhésion associé·e',
		adminPreviousYears: 'Années précédentes',
		adminAddYearMembership: '+ Ajouter une adhésion pour une autre année',
		adminModalAddMembershipTitle: 'Ajouter une adhésion pour une autre année',
		adminTotalReceived: 'Total reçu',
		adminDuesDonationLine: '{{dues}} cotisation · {{don}} don',
		adminAdminActionsLabel: 'Actions d’administration',
		adminDisableMember: 'Désactiver le membre',
		adminEnableMember: 'Réactiver le membre',
		adminGrantAdmin: 'Accorder le rôle admin',
		adminGrantAdminNoUser: 'Le membre n’a pas de compte de connexion lié.',
		adminAdminActionsFootnote:
			'La désactivation masque ce membre partout. Le rôle admin donne un accès complet à cette console.',
		adminConfirmDisable: 'Désactiver ce membre ? Il sera masqué partout.',
		adminConfirmEnable: 'Réactiver ce membre ?',
		adminConfirmGrantAdmin: 'Accorder à ce membre l’accès admin complet à la console d’adhésion ?',
		adminLakeManualLink: 'Saisir l’adresse manuellement →',
		adminLakeSearchLink: '← Utiliser la recherche d’adresse',
		adminLakeConfirmedLabel: 'Adresse sélectionnée',
		adminProfileCardTitle: 'Profil',
		adminMembershipCardTitle: 'Adhésion',
		adminPaymentRadioLabel: 'État du paiement',
		adminYearSelectLabel: 'Année',
		adminTierSelectLabel: 'Type',
		adminPrimaryContactSection: 'Contact principal',
		adminPreferencesSection: 'Préférences et notes',
		adminEditSubtitle: 'Modifier le profil',
		adminAccordionExpand: 'Afficher les paiements',
		adminCardPaymentStripe: 'Carte (Stripe)',
		adminDetailLoading: 'Chargement…',
		adminNoEmailDash: '—',
		adminNotesEmpty: '',
		adminConfirmDeletePayment: 'Supprimer ce paiement ?',
	},
};

export function mergeMemberUiStrings(locale: MemberLocale, base: Record<string, string>): Record<string, string> {
	return { ...base, ...adminMemberUiCopy[locale] };
}
