drop extension if exists "pg_net";


  create table "public"."members" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text not null,
    "primary_email" text,
    "secondary_email" text,
    "primary_phone" text,
    "secondary_phone" text,
    "lake_phone" text,
    "lake_civic_number" text,
    "lake_street_name" text,
    "primary_address" text,
    "primary_city" text,
    "primary_province" text,
    "primary_country" text,
    "primary_postal_code" text,
    "email_opt_in" boolean not null default false,
    "notes" text,
    "status" text not null default '''new''::text'::text
      );


alter table "public"."members" enable row level security;


  create table "public"."memberships" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "member_id" uuid not null default gen_random_uuid(),
    "year" smallint not null,
    "tier" text not null
      );


alter table "public"."memberships" enable row level security;


  create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "membership_id" uuid not null,
    "method" text,
    "amount" numeric,
    "date" date,
    "notes" text,
    "payment_id" text
      );


alter table "public"."payments" enable row level security;

CREATE UNIQUE INDEX "Members_pkey" ON public.members USING btree (id);

CREATE UNIQUE INDEX "Memberships_pkey" ON public.memberships USING btree (id);

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);

alter table "public"."members" add constraint "Members_pkey" PRIMARY KEY using index "Members_pkey";

alter table "public"."memberships" add constraint "Memberships_pkey" PRIMARY KEY using index "Memberships_pkey";

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."memberships" add constraint "Memberships_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE RESTRICT not valid;

alter table "public"."memberships" validate constraint "Memberships_member_id_fkey";

alter table "public"."memberships" add constraint "tier" CHECK ((tier = ANY (ARRAY['general'::text, 'associate'::text]))) not valid;

alter table "public"."memberships" validate constraint "tier";

alter table "public"."payments" add constraint "payments_membership_id_fkey" FOREIGN KEY (membership_id) REFERENCES public.memberships(id) ON DELETE RESTRICT not valid;

alter table "public"."payments" validate constraint "payments_membership_id_fkey";

alter table "public"."payments" add constraint "payments_method_check" CHECK ((method = ANY (ARRAY['stripe'::text, 'e-transfer'::text, 'cheque'::text, 'cash'::text, 'unknown'::text]))) not valid;

alter table "public"."payments" validate constraint "payments_method_check";

grant delete on table "public"."members" to "anon";

grant insert on table "public"."members" to "anon";

grant references on table "public"."members" to "anon";

grant select on table "public"."members" to "anon";

grant trigger on table "public"."members" to "anon";

grant truncate on table "public"."members" to "anon";

grant update on table "public"."members" to "anon";

grant delete on table "public"."members" to "authenticated";

grant insert on table "public"."members" to "authenticated";

grant references on table "public"."members" to "authenticated";

grant select on table "public"."members" to "authenticated";

grant trigger on table "public"."members" to "authenticated";

grant truncate on table "public"."members" to "authenticated";

grant update on table "public"."members" to "authenticated";

grant delete on table "public"."members" to "service_role";

grant insert on table "public"."members" to "service_role";

grant references on table "public"."members" to "service_role";

grant select on table "public"."members" to "service_role";

grant trigger on table "public"."members" to "service_role";

grant truncate on table "public"."members" to "service_role";

grant update on table "public"."members" to "service_role";

grant delete on table "public"."memberships" to "anon";

grant insert on table "public"."memberships" to "anon";

grant references on table "public"."memberships" to "anon";

grant select on table "public"."memberships" to "anon";

grant trigger on table "public"."memberships" to "anon";

grant truncate on table "public"."memberships" to "anon";

grant update on table "public"."memberships" to "anon";

grant delete on table "public"."memberships" to "authenticated";

grant insert on table "public"."memberships" to "authenticated";

grant references on table "public"."memberships" to "authenticated";

grant select on table "public"."memberships" to "authenticated";

grant trigger on table "public"."memberships" to "authenticated";

grant truncate on table "public"."memberships" to "authenticated";

grant update on table "public"."memberships" to "authenticated";

grant delete on table "public"."memberships" to "service_role";

grant insert on table "public"."memberships" to "service_role";

grant references on table "public"."memberships" to "service_role";

grant select on table "public"."memberships" to "service_role";

grant trigger on table "public"."memberships" to "service_role";

grant truncate on table "public"."memberships" to "service_role";

grant update on table "public"."memberships" to "service_role";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";


